### ISSUE TITLE
Marquee

### ISSUE THREAD

**Issue by Dariush-Mehdiaraghi** [verein-baustell/tram-und-bass#5]
There are [marquee](https://github.com/orgs/verein-baustell/projects/1?pane=issue&itemId=68333317) on titles that should not overflow in the first place (see screenshot).
<img width="396" alt="Bildschirmfoto 2024-11-03 um 23 04 31" src="https://github.com/user-attachments/assets/4331b122-d517-40a8-80f9-9d5a54153089">

**Comment by worstheadache** [comment]
I can't reproduce this, when does this happen? But potentially, checkOverflow() doesn't check the correct container.

**Comment by Dariush-Mehdiaraghi** [comment]
> I can't reproduce this, when does this happen? But potentially, checkOverflow() doesn't check the correct container.

It happened in safari desktop
