### ISSUE TITLE
views don't align correct anymore

### ISSUE THREAD

**Issue by fabifree** [verein-baustell/tram-und-bass#7]
<img width="540" alt="Screenshot 2024-11-08 at 17 57 53" src="https://github.com/user-attachments/assets/81a5d37c-9814-4bc1-8275-584c9cdb52bc">
should be aligned right

<img width="1261" alt="Screenshot 2024-11-08 at 17 57 43" src="https://github.com/user-attachments/assets/f6a35495-bf7b-451f-bff7-dce56fc4a2cf">
too wide

**Comment by worstheadache** [comment]
Adjusted top to width: 400px; 
Adjusted bottom to width: 480px as specified in design file.
